baseURL = 'https://kstr0.xyz/'
languageCode = 'en-us'
title = 'Kstr0'

theme = 'hugo-blog-awesome'
defaultContentLanguage = "en"

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true

# Menu config
[menu]
  [[menu.main]]
    pageRef="posts"
    name = 'Posts'
    url = '/posts/'
    weight = 20

#defines parameters (see theme docs)
[params]
  sitename = "Awesome hugo blog"
  defaultColor = "dark" 
  description = "Minimal Hugo blog theme with light and dark mode support"

[params.author]
  avatar = "avatar.png"
  intro = "Kstr-0"
  name = "Kstr-0"
  description = "Hey there! I'm Kstr-0, a computer hobbyist and tinkerer from Glasgow. Welcome to my little online space!"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/kstr0git"
