# The URL the site will be built for
base_url = "https://kstr0.xyz"
title = "kstr0"
description = "I like to take things apart"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

theme = "fisher"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
github_account = "kstr0git"
author = "kstr0"
